{{- if and (eq .Values.coldStorage.backend "s3") .Values.coldStorage.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ursula.fullname" . }}-s3
  labels:
    {{- include "ursula.labels" . | nindent 4 }}
type: Opaque
stringData:
  URSULA_COLD_S3_ACCESS_KEY_ID: {{ .Values.coldStorage.s3.accessKeyId | quote }}
  URSULA_COLD_S3_SECRET_ACCESS_KEY: {{ .Values.coldStorage.s3.secretAccessKey | quote }}
{{- end }}
